services:
    nginx:
        image: nginx:latest
        ports:
            - "127.0.0.1:3000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "127.0.0.1:3306:3306"
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "127.0.0.1:8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_ABSOLUTE_URI=https://projects.maxkruiswegt.com/phpmyadmin/
        restart: unless-stopped
volumes:
    mysqldata: {}
